format_version: 3
pipelines:
  dcc-quickstart-ci:
    group: Application
    materials:
      repo:
        git: https://github.com/denis1729/task.git
        branch: master
        whitelist:
            - webaplication/**/*
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    working_directory: webaplication
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble
              artifacts:
                - build:
                    source: webaplication/build/libs/*.jar
                    destination: jar
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    working_directory: webaplication
                    command: ./gradlew
                    arguments:
                      - test
              artifacts:
                - build:
                    source: webaplication/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: webaplication/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - Code_Quality:
          jobs:
            Sonarqube:
              tasks:
                - exec:
                    working_directory: webaplication
                    command: ./gradlew
                    arguments:
                      - sonarqube  
            Owasp:
              tasks:
                - exec:
                    working_directory: webaplication
                    command: ./gradlew
                    arguments:
                      - dependencyCheckAnalyze
              artifacts:
                - build:
                    source: webaplication/build/reports/**/*
                    destination: html
              tabs:
                OWASP: html/dependency-check-report.html
